In [1]:
import pandas as pd

Malaria  = pd.read_excel("Malaria Training dataset.xlsx")

In [2]:
Malaria.shape

(5000, 28)

In [3]:
Malaria.head(2)

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
0,MLR00001,Male,55,50+,University,Employed,Married/Cohabiting,Kigali City,Nyarugenge,-1.95,...,Not applicable,No,Not applicable,NaT,Recovered,2026-10-28,NaN,Oct,Q4,2026
1,MLR00002,Female,47,35-49,Secondary,Farmer,Married/Cohabiting,Eastern,Kirehe,-2.26,...,No,Yes,ACT,2026-12-18,Recovered,2026-12-19,0.0,Dec,Q4,2026

**Dealing with missing values**

Identify missing values

In [4]:
Malaria.isna()

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False

In [5]:
Malaria.isna().sum()

Patient_ID                 0
Sex                        8
Age                        0
Age_Group                  0
Education                510
Occupation                 0
Marital_Status             0
Province                   0
District                   0
Latitude                   0
Longitude                  0
Consultation_Date          0
Malaria_Test_Type          0
Malaria_Result             0
Case_Status                0
Fever                      0
Temperature_C              0
Severe_Malaria             0
Pregnancy_Status           0
Treatment_Received         0
Treatment_Type             0
Treatment_Date          3357
Outcome                    0
Outcome_Date             201
Treatment_Delay_Days    3357
Reporting_Month            0
Reporting_Quarter          0
Reporting_Year             0
dtype: int64

In [6]:
MISSING = Malaria.isna().sum()
MISSING[MISSING>0]

Sex                        8
Education                510
Treatment_Date          3357
Outcome_Date             201
Treatment_Delay_Days    3357
dtype: int64

In [7]:
# Row with At least one missing

Malaria[Malaria.isna().any(axis=1)]

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
0,MLR00001,Male,55,50+,University,Employed,Married/Cohabiting,Kigali City,Nyarugenge,-1.95,...,Not applicable,No,Not applicable,NaT,Recovered,2026-10-28,NaN,Oct,Q4,2026
2,MLR00003,Female,69,50+,Primary,Self-employed,Married/Cohabiting,Southern,Nyanza,-2.35,...,Not applicable,No,Not applicable,NaT,Recovered,2026-02-11,NaN,Feb,Q1,2026
4,MLR00005,Male,47,35-49,Secondary,Unemployed,Single,Eastern,Kayonza,-1.91,...,Not applicable,No,Not applicable,NaT,Recovered,2026-06-07,NaN,Jun,Q2,2026
6,MLR00007,Male,31,25-34,University,Unemployed,Married/Cohabiting,Western,Rutsiro,-1.94,...,Not applicable,No,Not applicable,NaT,Recovered,2026-06-04,NaN,Jun,Q2,2026
7,MLR00008,Female,54,50+,NaN,Farmer,Married/Cohabiting,Western,Karongi,-2.15,...,Not applicable,No,Not applicable,NaT,Recovered,2026-10-30,NaN,Oct,Q4,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,MLR04996,Female,23,15-24,Primary,Student,Married/Cohabiting,Southern,Muhanga,-2.08,...,No,No,Not applicable,NaT,Recovered,2026-08-25,NaN,Aug,Q3,2026
4996,MLR04997,Female,35,35-49,Secondary,Student,Married/Cohabiting,Eastern,Gatsibo,-1.60,...,No,No,Not applicable,NaT,Recovered,2026-07-19,NaN,Jul,Q3,2026
4997,MLR04998,Female,6,5-14,Primary,Student,Married/Cohabiting,Kigali City,Gasabo,-1.93,...,Not applicable,No,Not applicable,NaT,Recovered,2026-08-31,NaN,Aug,Q3,2026
4998,MLR04999,Female,70,50+,University,Farmer,Divorced/Separated,Eastern,Bugesera,-2.21,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026
4999,MLR05000,Male,17,15-24,Primary,Employed,Married/Cohabiting,Northern,Musanze,-1.50,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026

In [11]:
Malaria[Malaria.isna().sum(axis=1) >3]

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
369,MLR00370,Male,51,50+,NaN,Farmer,Married/Cohabiting,Eastern,Kayonza,-1.91,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Oct,Q4,2026
1009,MLR01010,Female,6,5-14,NaN,Student,Single,Northern,Gakenke,-1.69,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jan,Q1,2026
1121,MLR01122,Female,55,50+,NaN,Student,Single,Southern,Huye,-2.60,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Oct,Q4,2026
1260,MLR01261,Male,9,5-14,NaN,Unemployed,Married/Cohabiting,Western,Rusizi,-2.49,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Sep,Q3,2026
1371,MLR01372,Female,48,35-49,NaN,Student,Single,Western,Rusizi,-2.49,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jan,Q1,2026
1373,MLR01374,Male,18,15-24,NaN,Farmer,Single,Southern,Nyaruguru,-2.70,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Nov,Q4,2026
1595,MLR01596,Female,29,25-34,NaN,Farmer,Married/Cohabiting,Northern,Gicumbi,-1.57,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Dec,Q4,2026
1966,MLR01967,Female,26,25-34,NaN,Self-employed,Single,Western,Nyamasheke,-2.34,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jul,Q3,2026
2182,MLR02183,Male,64,50+,NaN,Farmer,Married/Cohabiting,Western,Karongi,-2.15,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Dec,Q4,2026
2486,MLR02487,Male,37,35-49,NaN,Self-employed,Single,Southern,Nyanza,-2.35,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Sep,Q3,2026
2532,MLR02533,Male,15,15-24,NaN,Self-employed,Married/Cohabiting,Western,Rubavu,-1.68,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Nov,Q4,2026
3365,MLR03366,Female,34,25-34,NaN,Farmer,Married/Cohabiting,Northern,Rulindo,-1.72,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Aug,Q3,2026
3436,MLR03437,Female,35,35-49,NaN,Employed,Single,Southern,Nyanza,-2.35,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Apr,Q2,2026
3681,MLR03682,Male,18,15-24,NaN,Employed,Married/Cohabiting,Western,Rusizi,-2.49,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Aug,Q3,2026
3942,MLR03943,Male,13,5-14,NaN,Student,Married/Cohabiting,Western,Rutsiro,-1.94,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Mar,Q1,2026
4062,MLR04063,Female,41,35-49,NaN,Farmer,Married/Cohabiting,Northern,Burera,-1.48,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jan,Q1,2026
4072,MLR04073,Male,8,5-14,NaN,Unemployed,Widowed,Eastern,Rwamagana,-1.95,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Apr,Q2,2026
4105,MLR04106,Male,32,25-34,NaN,Student,Married/Cohabiting,Eastern,Gatsibo,-1.60,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Nov,Q4,2026
4289,MLR04290,Male,19,15-24,NaN,Self-employed,Married/Cohabiting,Eastern,Kayonza,-1.91,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Feb,Q1,2026
4344,MLR04345,Female,53,50+,NaN,Student,Widowed,Eastern,Kirehe,-2.26,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jun,Q2,2026
4728,MLR04729,Female,20,15-24,NaN,Self-employed,Married/Cohabiting,Western,Rutsiro,-1.94,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Jul,Q3,2026
4853,MLR04854,Female,24,15-24,NaN,Farmer,Married/Cohabiting,Western,Nyamasheke,-2.34,...,No,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Oct,Q4,2026
4967,MLR04968,Male,47,35-49,NaN,Student,Married/Cohabiting,Northern,Musanze,-1.50,...,Not applicable,No,Not applicable,NaT,Lost to follow-up,NaT,NaN,Nov,Q4,2026

In [12]:
#Remove rows if all is missing
Malaria.dropna(how="all")

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
0,MLR00001,Male,55,50+,University,Employed,Married/Cohabiting,Kigali City,Nyarugenge,-1.95,...,Not applicable,No,Not applicable,NaT,Recovered,2026-10-28,NaN,Oct,Q4,2026
1,MLR00002,Female,47,35-49,Secondary,Farmer,Married/Cohabiting,Eastern,Kirehe,-2.26,...,No,Yes,ACT,2026-12-18,Recovered,2026-12-19,0.0,Dec,Q4,2026
2,MLR00003,Female,69,50+,Primary,Self-employed,Married/Cohabiting,Southern,Nyanza,-2.35,...,Not applicable,No,Not applicable,NaT,Recovered,2026-02-11,NaN,Feb,Q1,2026
3,MLR00004,Female,29,25-34,Primary,Employed,Single,Eastern,Kirehe,-2.26,...,No,Yes,ACT,2026-05-12,Recovered,2026-05-15,0.0,May,Q2,2026
4,MLR00005,Male,47,35-49,Secondary,Unemployed,Single,Eastern,Kayonza,-1.91,...,Not applicable,No,Not applicable,NaT,Recovered,2026-06-07,NaN,Jun,Q2,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,MLR04996,Female,23,15-24,Primary,Student,Married/Cohabiting,Southern,Muhanga,-2.08,...,No,No,Not applicable,NaT,Recovered,2026-08-25,NaN,Aug,Q3,2026
4996,MLR04997,Female,35,35-49,Secondary,Student,Married/Cohabiting,Eastern,Gatsibo,-1.60,...,No,No,Not applicable,NaT,Recovered,2026-07-19,NaN,Jul,Q3,2026
4997,MLR04998,Female,6,5-14,Primary,Student,Married/Cohabiting,Kigali City,Gasabo,-1.93,...,Not applicable,No,Not applicable,NaT,Recovered,2026-08-31,NaN,Aug,Q3,2026
4998,MLR04999,Female,70,50+,University,Farmer,Divorced/Separated,Eastern,Bugesera,-2.21,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026
4999,MLR05000,Male,17,15-24,Primary,Employed,Married/Cohabiting,Northern,Musanze,-1.50,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026

In [15]:
#Drop any row with missing

No_Missing = Malaria.dropna()

In [16]:
No_Missing.shape

(1414, 28)

In [17]:
#Remove if Age is missing

Malaria.dropna(subset=["Age"])

,Patient_ID,Sex,Age,Age_Group,Education,Occupation,Marital_Status,Province,District,Latitude,...,Pregnancy_Status,Treatment_Received,Treatment_Type,Treatment_Date,Outcome,Outcome_Date,Treatment_Delay_Days,Reporting_Month,Reporting_Quarter,Reporting_Year
0,MLR00001,Male,55,50+,University,Employed,Married/Cohabiting,Kigali City,Nyarugenge,-1.95,...,Not applicable,No,Not applicable,NaT,Recovered,2026-10-28,NaN,Oct,Q4,2026
1,MLR00002,Female,47,35-49,Secondary,Farmer,Married/Cohabiting,Eastern,Kirehe,-2.26,...,No,Yes,ACT,2026-12-18,Recovered,2026-12-19,0.0,Dec,Q4,2026
2,MLR00003,Female,69,50+,Primary,Self-employed,Married/Cohabiting,Southern,Nyanza,-2.35,...,Not applicable,No,Not applicable,NaT,Recovered,2026-02-11,NaN,Feb,Q1,2026
3,MLR00004,Female,29,25-34,Primary,Employed,Single,Eastern,Kirehe,-2.26,...,No,Yes,ACT,2026-05-12,Recovered,2026-05-15,0.0,May,Q2,2026
4,MLR00005,Male,47,35-49,Secondary,Unemployed,Single,Eastern,Kayonza,-1.91,...,Not applicable,No,Not applicable,NaT,Recovered,2026-06-07,NaN,Jun,Q2,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,MLR04996,Female,23,15-24,Primary,Student,Married/Cohabiting,Southern,Muhanga,-2.08,...,No,No,Not applicable,NaT,Recovered,2026-08-25,NaN,Aug,Q3,2026
4996,MLR04997,Female,35,35-49,Secondary,Student,Married/Cohabiting,Eastern,Gatsibo,-1.60,...,No,No,Not applicable,NaT,Recovered,2026-07-19,NaN,Jul,Q3,2026
4997,MLR04998,Female,6,5-14,Primary,Student,Married/Cohabiting,Kigali City,Gasabo,-1.93,...,Not applicable,No,Not applicable,NaT,Recovered,2026-08-31,NaN,Aug,Q3,2026
4998,MLR04999,Female,70,50+,University,Farmer,Divorced/Separated,Eastern,Bugesera,-2.21,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026
4999,MLR05000,Male,17,15-24,Primary,Employed,Married/Cohabiting,Northern,Musanze,-1.50,...,Not applicable,No,Not applicable,NaT,Recovered,2026-12-16,NaN,Dec,Q4,2026

**Replace missing Values**

In [19]:
Malaria["Education"].unique()

array(['University', 'Secondary', 'Primary', nan], dtype=object)

In [20]:
#Replace with a label/text

Malaria["Education"] = Malaria["Education"].fillna("No formal education")
Malaria["Education"].unique()

array(['University', 'Secondary', 'Primary', 'No formal education'],
      dtype=object)

In [21]:
### Replace with Mean of Age

Malaria["Age"] = Malaria["Age"].fillna(Malaria["Age"].mean())

In [24]:
Malaria["Sex"].value_counts()

Sex
Female    2529
Male      2463
Name: count, dtype: int64

In [25]:
## Replace Sex missing with female

Malaria["Sex"] = Malaria["Sex"].fillna("Female")

In [28]:
Missing = Malaria.isna().sum()
Missing[Missing>0]

Treatment_Date          3357
Outcome_Date             201
Treatment_Delay_Days    3357
dtype: int64

**DEALING WITH DUPLICATES**

Identify the duplicates

In [30]:
Malaria.duplicated().sum()

np.int64(0)

In [31]:
Test = pd.DataFrame({
    "Name": ["A","B","C","B","E"],
    "Age" :  [11,31,24,31,11]
})
Test

  Name  Age
0    A   11
1    B   31
2    C   24
3    B   31
4    E   11

In [32]:
Test.duplicated().sum()

np.int64(1)

In [34]:
#Which rows duplicate

Test[Test.duplicated(keep= False)]

  Name  Age
1    B   31
3    B   31

In [35]:
Test = Test.drop_duplicates()
Test

  Name  Age
0    A   11
1    B   31
2    C   24
4    E   11

In [38]:
#Check duplicate on Identifier

Malaria[Malaria.duplicated(subset = ["Patient_ID"], keep = False)]

Empty DataFrame
Columns: [Patient_ID, Sex, Age, Age_Group, Education, Occupation, Marital_Status, Province, District, Latitude, Longitude, Consultation_Date, Malaria_Test_Type, Malaria_Result, Case_Status, Fever, Temperature_C, Severe_Malaria, Pregnancy_Status, Treatment_Received, Treatment_Type, Treatment_Date, Outcome, Outcome_Date, Treatment_Delay_Days, Reporting_Month, Reporting_Quarter, Reporting_Year]
Index: []

[0 rows x 28 columns]

**DEALING WITH INCONSISTENCIES**

Spelling

In [39]:
Malaria["Occupation"].unique()

array(['Employed', 'Farmer', 'Self-employed', 'Unemployed', 'Student'],
      dtype=object)

In [40]:
Malaria["Occupation"].value_counts()

Occupation
Farmer           1745
Self-employed    1033
Student           900
Employed          807
Unemployed        515
Name: count, dtype: int64

In [41]:
## I want students to be unemployed

Malaria["Occupation"] = Malaria["Occupation"].replace({
    "Student" : "Unemployed"
})

In [42]:
Malaria["Occupation"].value_counts()

Occupation
Farmer           1745
Unemployed       1415
Self-employed    1033
Employed          807
Name: count, dtype: int64

**MERGING DATA FRAMES**

In [50]:
List1 = pd.DataFrame({
    "id" : [1,2,3],
    "age" : [25,30,22]
})

List2 = pd.DataFrame({
    "id": [1,2,3],
    "education": ["Primary","Secondary","Higher"]
})

In [51]:
List1

   id  age
0   1   25
1   2   30
2   3   22

In [52]:
List2

   id  education
0   1    Primary
1   2  Secondary
2   3     Higher

In [53]:
Full_list = pd.merge(
    List1,
    List2,
    on = "id",
    how="left",
    validate = "one_to_one"
)

In [54]:
Full_list

   id  age  education
0   1   25    Primary
1   2   30  Secondary
2   3   22     Higher

**Export your Dataframe**

In [55]:
#Export in Jupyter notebook

Malaria.to_excel("Malaria_clean.xlsx", index = False)

In [56]:
#Export to a computer folder

Malaria.to_excel("/Users/semutojeanclaude/Library/CloudStorage/GoogleDrive-mzeedrive3@gmail.com/My Drive/OPTMA Data Solutions/Training/Python Training/Malaria_clean.xlsx", index = False)